# Generated by Django 6.0.7 on 2026-07-26 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='Organization',
            new_name='organization',
        ),
    ]
